package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.AdjustBookps;
import com.cn.interfacedocument.entity.AdjustBookpsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface AdjustBookpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(AdjustBookpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(AdjustBookpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(AdjustBookps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(AdjustBookps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<AdjustBookps> selectByExample(AdjustBookpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    AdjustBookps selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") AdjustBookps record, @Param("example") AdjustBookpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") AdjustBookps record, @Param("example") AdjustBookpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(AdjustBookps record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ADJUST_BOOKPS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(AdjustBookps record);
}