package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.Cause;
import com.cn.interfacedocument.entity.CauseExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface CauseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(CauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(CauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(Cause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(Cause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<Cause> selectByExample(CauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    Cause selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") Cause record, @Param("example") CauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") Cause record, @Param("example") CauseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(Cause record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(Cause record);
}