package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.DataOnlineLawCaseCount;
import com.cn.interfacedocument.entity.DataOnlineLawCaseCountExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DataOnlineLawCaseCountMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(DataOnlineLawCaseCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(DataOnlineLawCaseCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Integer onlinelawcasecount);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(DataOnlineLawCaseCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(DataOnlineLawCaseCount record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DataOnlineLawCaseCount> selectByExample(DataOnlineLawCaseCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") DataOnlineLawCaseCount record, @Param("example") DataOnlineLawCaseCountExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table data_online_law_case_count
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") DataOnlineLawCaseCount record, @Param("example") DataOnlineLawCaseCountExample example);
}