package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.DisputesAttachment;
import com.cn.interfacedocument.entity.DisputesAttachmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DisputesAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(DisputesAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(DisputesAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(DisputesAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(DisputesAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DisputesAttachment> selectByExample(DisputesAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    DisputesAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") DisputesAttachment record, @Param("example") DisputesAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") DisputesAttachment record, @Param("example") DisputesAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(DisputesAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(DisputesAttachment record);
}