package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.DisputesData;
import com.cn.interfacedocument.entity.DisputesDataExample;
import com.cn.interfacedocument.entity.DisputesDataWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DisputesDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(DisputesDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(DisputesDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DisputesDataWithBLOBs> selectByExampleWithBLOBs(DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DisputesData> selectByExample(DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    DisputesDataWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") DisputesDataWithBLOBs record, @Param("example") DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DisputesDataWithBLOBs record, @Param("example") DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") DisputesData record, @Param("example") DisputesDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(DisputesDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DisputesDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(DisputesData record);
}