package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.DisputesScore;
import com.cn.interfacedocument.entity.DisputesScoreExample;
import com.cn.interfacedocument.entity.DisputesScoreWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DisputesScoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(DisputesScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(DisputesScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DisputesScoreWithBLOBs> selectByExampleWithBLOBs(DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<DisputesScore> selectByExample(DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    DisputesScoreWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") DisputesScoreWithBLOBs record, @Param("example") DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") DisputesScoreWithBLOBs record, @Param("example") DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") DisputesScore record, @Param("example") DisputesScoreExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(DisputesScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(DisputesScoreWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table DISPUTES_SCORE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(DisputesScore record);
}