package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.EvaluatePersonnel;
import com.cn.interfacedocument.entity.EvaluatePersonnelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EvaluatePersonnelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(EvaluatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(EvaluatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(EvaluatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(EvaluatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<EvaluatePersonnel> selectByExample(EvaluatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    EvaluatePersonnel selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") EvaluatePersonnel record, @Param("example") EvaluatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") EvaluatePersonnel record, @Param("example") EvaluatePersonnelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(EvaluatePersonnel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table EVALUATE_PERSONNEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(EvaluatePersonnel record);
}