package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.GovAccountmessage;
import com.cn.interfacedocument.entity.GovAccountmessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface GovAccountmessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(GovAccountmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(GovAccountmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(GovAccountmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(GovAccountmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<GovAccountmessage> selectByExample(GovAccountmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    GovAccountmessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") GovAccountmessage record, @Param("example") GovAccountmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") GovAccountmessage record, @Param("example") GovAccountmessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeySelective(GovAccountmessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table GOV_ACCOUNTMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKey(GovAccountmessage record);
}