package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.IndictmentData;
import com.cn.interfacedocument.entity.IndictmentDataExample;
import com.cn.interfacedocument.entity.IndictmentDataWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IndictmentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(IndictmentDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(IndictmentDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<IndictmentDataWithBLOBs> selectByExampleWithBLOBs(IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<IndictmentData> selectByExample(IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    IndictmentDataWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") IndictmentDataWithBLOBs record, @Param("example") IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") IndictmentDataWithBLOBs record, @Param("example") IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") IndictmentData record, @Param("example") IndictmentDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(IndictmentDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(IndictmentDataWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table INDICTMENT_DATA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(IndictmentData record);
}