package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawCaseSignature;
import com.cn.interfacedocument.entity.LawCaseSignatureExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawCaseSignatureMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(LawCaseSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(LawCaseSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawCaseSignature> selectByExampleWithBLOBs(LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawCaseSignature> selectByExample(LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    LawCaseSignature selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawCaseSignature record, @Param("example") LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawCaseSignature record, @Param("example") LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") LawCaseSignature record, @Param("example") LawCaseSignatureExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeySelective(LawCaseSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawCaseSignature record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_SIGNATURE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKey(LawCaseSignature record);
}