package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawCaseDossierAttachment;
import com.cn.interfacedocument.entity.LawCaseDossierAttachmentExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawCaseDossierAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawCaseDossierAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawCaseDossierAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawCaseDossierAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawCaseDossierAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawCaseDossierAttachment> selectByExample(LawCaseDossierAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawCaseDossierAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawCaseDossierAttachment record, @Param("example") LawCaseDossierAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawCaseDossierAttachment record, @Param("example") LawCaseDossierAttachmentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawCaseDossierAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_DOSSIER_ATTACHMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawCaseDossierAttachment record);
}