package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawCaseOrigiginDetail;
import com.cn.interfacedocument.entity.LawCaseOrigiginDetailExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawCaseOrigiginDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawCaseOrigiginDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawCaseOrigiginDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawCaseOrigiginDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawCaseOrigiginDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawCaseOrigiginDetail> selectByExample(LawCaseOrigiginDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawCaseOrigiginDetail selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawCaseOrigiginDetail record, @Param("example") LawCaseOrigiginDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawCaseOrigiginDetail record, @Param("example") LawCaseOrigiginDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawCaseOrigiginDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_CASE_ORIGIGIN_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawCaseOrigiginDetail record);
}