package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawMscheme;
import com.cn.interfacedocument.entity.LawMschemeExample;
import com.cn.interfacedocument.entity.LawMschemeWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawMschemeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawMschemeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawMschemeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawMschemeWithBLOBs> selectByExampleWithBLOBs(LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawMscheme> selectByExample(LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawMschemeWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawMschemeWithBLOBs record, @Param("example") LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawMschemeWithBLOBs record, @Param("example") LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawMscheme record, @Param("example") LawMschemeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawMschemeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawMschemeWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_MSCHEME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawMscheme record);
}