package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawNoDisputeFact;
import com.cn.interfacedocument.entity.LawNoDisputeFactExample;
import com.cn.interfacedocument.entity.LawNoDisputeFactWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawNoDisputeFactMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawNoDisputeFactWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawNoDisputeFactWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawNoDisputeFactWithBLOBs> selectByExampleWithBLOBs(LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawNoDisputeFact> selectByExample(LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawNoDisputeFactWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawNoDisputeFactWithBLOBs record, @Param("example") LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawNoDisputeFactWithBLOBs record, @Param("example") LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawNoDisputeFact record, @Param("example") LawNoDisputeFactExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawNoDisputeFactWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawNoDisputeFactWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_NO_DISPUTE_FACT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawNoDisputeFact record);
}