package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitPaper;
import com.cn.interfacedocument.entity.LawSuitPaperExample;
import com.cn.interfacedocument.entity.LawSuitPaperWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitPaperMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(LawSuitPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(LawSuitPaperWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitPaperWithBLOBs> selectByExampleWithBLOBs(LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitPaper> selectByExample(LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitPaperWithBLOBs record, @Param("example") LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawSuitPaperWithBLOBs record, @Param("example") LawSuitPaperExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PAPER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") LawSuitPaper record, @Param("example") LawSuitPaperExample example);
}