package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitPriSession;
import com.cn.interfacedocument.entity.LawSuitPriSessionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitPriSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawSuitPriSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawSuitPriSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawSuitPriSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawSuitPriSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawSuitPriSession> selectByExample(LawSuitPriSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawSuitPriSession selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitPriSession record, @Param("example") LawSuitPriSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawSuitPriSession record, @Param("example") LawSuitPriSessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitPriSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PRI_SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawSuitPriSession record);
}