package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitPerson;
import com.cn.interfacedocument.entity.LawSuitPersonExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawSuitPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawSuitPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawSuitPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawSuitPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawSuitPerson> selectByExample(LawSuitPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawSuitPerson selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitPerson record, @Param("example") LawSuitPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawSuitPerson record, @Param("example") LawSuitPersonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawSuitPerson record);
}