package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitJudicialRecord;
import com.cn.interfacedocument.entity.LawSuitJudicialRecordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitJudicialRecordMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(LawSuitJudicialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(LawSuitJudicialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitJudicialRecord> selectByExampleWithBLOBs(LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitJudicialRecord> selectByExample(LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    LawSuitJudicialRecord selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitJudicialRecord record, @Param("example") LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawSuitJudicialRecord record, @Param("example") LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") LawSuitJudicialRecord record, @Param("example") LawSuitJudicialRecordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitJudicialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawSuitJudicialRecord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_JUDICIAL_RECORD
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKey(LawSuitJudicialRecord record);
}