package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawsAndRegulations;
import com.cn.interfacedocument.entity.LawsAndRegulationsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawsAndRegulationsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawsAndRegulations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawsAndRegulations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawsAndRegulations> selectByExampleWithBLOBs(LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawsAndRegulations> selectByExample(LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawsAndRegulations selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawsAndRegulations record, @Param("example") LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawsAndRegulations record, @Param("example") LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawsAndRegulations record, @Param("example") LawsAndRegulationsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawsAndRegulations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawsAndRegulations record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAWS_AND_REGULATIONS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawsAndRegulations record);
}