package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitNemessage;
import com.cn.interfacedocument.entity.LawSuitNemessageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitNemessageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(LawSuitNemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(LawSuitNemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitNemessage> selectByExampleWithBLOBs(LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<LawSuitNemessage> selectByExample(LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    LawSuitNemessage selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitNemessage record, @Param("example") LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawSuitNemessage record, @Param("example") LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") LawSuitNemessage record, @Param("example") LawSuitNemessageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitNemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawSuitNemessage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByPrimaryKey(LawSuitNemessage record);
}