package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitDetail;
import com.cn.interfacedocument.entity.LawSuitDetailExample;
import com.cn.interfacedocument.entity.LawSuitDetailWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawSuitDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawSuitDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawSuitDetailWithBLOBs> selectByExampleWithBLOBs(LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawSuitDetail> selectByExample(LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawSuitDetailWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitDetailWithBLOBs record, @Param("example") LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") LawSuitDetailWithBLOBs record, @Param("example") LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawSuitDetail record, @Param("example") LawSuitDetailExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(LawSuitDetailWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_DETAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawSuitDetail record);
}