package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.LawSuitMeetting;
import com.cn.interfacedocument.entity.LawSuitMeettingExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface LawSuitMeettingMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(LawSuitMeettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(LawSuitMeettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(LawSuitMeetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(LawSuitMeetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<LawSuitMeetting> selectByExample(LawSuitMeettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    LawSuitMeetting selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") LawSuitMeetting record, @Param("example") LawSuitMeettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") LawSuitMeetting record, @Param("example") LawSuitMeettingExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(LawSuitMeetting record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table LAW_SUIT_MEETTING
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(LawSuitMeetting record);
}