package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.MediationType;
import com.cn.interfacedocument.entity.MediationTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MediationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(MediationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(MediationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(MediationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(MediationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<MediationType> selectByExample(MediationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    MediationType selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") MediationType record, @Param("example") MediationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") MediationType record, @Param("example") MediationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(MediationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MEDIATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(MediationType record);
}