package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.MobileVersionUpdate;
import com.cn.interfacedocument.entity.MobileVersionUpdateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MobileVersionUpdateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(MobileVersionUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(MobileVersionUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(MobileVersionUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(MobileVersionUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<MobileVersionUpdate> selectByExample(MobileVersionUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    MobileVersionUpdate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") MobileVersionUpdate record, @Param("example") MobileVersionUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") MobileVersionUpdate record, @Param("example") MobileVersionUpdateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(MobileVersionUpdate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MOBILE_VERSION_UPDATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(MobileVersionUpdate record);
}