package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.Modal;
import com.cn.interfacedocument.entity.ModalExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ModalMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<Modal> selectByExampleWithBLOBs(ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<Modal> selectByExample(ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    Modal selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") Modal record, @Param("example") ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") Modal record, @Param("example") ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") Modal record, @Param("example") ModalExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(Modal record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MODAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(Modal record);
}