package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.OrganizationType;
import com.cn.interfacedocument.entity.OrganizationTypeExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface OrganizationTypeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(OrganizationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(OrganizationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(OrganizationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(OrganizationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<OrganizationType> selectByExample(OrganizationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    OrganizationType selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") OrganizationType record, @Param("example") OrganizationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") OrganizationType record, @Param("example") OrganizationTypeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(OrganizationType record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORGANIZATION_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(OrganizationType record);
}