package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.Session;
import com.cn.interfacedocument.entity.SessionExample;
import com.cn.interfacedocument.entity.SessionWithBLOBs;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<SessionWithBLOBs> selectByExampleWithBLOBs(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<Session> selectByExample(SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    SessionWithBLOBs selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") SessionWithBLOBs record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") SessionWithBLOBs record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") Session record, @Param("example") SessionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(SessionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SESSION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(Session record);
}