package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.UserAuthenticate;
import com.cn.interfacedocument.entity.UserAuthenticateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface UserAuthenticateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(UserAuthenticateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(UserAuthenticateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(UserAuthenticate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(UserAuthenticate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<UserAuthenticate> selectByExample(UserAuthenticateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    UserAuthenticate selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") UserAuthenticate record, @Param("example") UserAuthenticateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") UserAuthenticate record, @Param("example") UserAuthenticateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(UserAuthenticate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USER_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(UserAuthenticate record);
}