package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.VisitHistory;
import com.cn.interfacedocument.entity.VisitHistoryExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface VisitHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(VisitHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(VisitHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(VisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(VisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<VisitHistory> selectByExample(VisitHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    VisitHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") VisitHistory record, @Param("example") VisitHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") VisitHistory record, @Param("example") VisitHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(VisitHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table VISIT_HISTORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(VisitHistory record);
}