package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.XjqCalendars;
import com.cn.interfacedocument.entity.XjqCalendarsExample;
import com.cn.interfacedocument.entity.XjqCalendarsKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XjqCalendarsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(XjqCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(XjqCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(XjqCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<XjqCalendars> selectByExampleWithBLOBs(XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<XjqCalendars> selectByExample(XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    XjqCalendars selectByPrimaryKey(XjqCalendarsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") XjqCalendars record, @Param("example") XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") XjqCalendars record, @Param("example") XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") XjqCalendars record, @Param("example") XjqCalendarsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(XjqCalendars record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_CALENDARS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(XjqCalendars record);
}