package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.XjqPausedTriggerGrpsExample;
import com.cn.interfacedocument.entity.XjqPausedTriggerGrpsKey;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XjqPausedTriggerGrpsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int countByExample(XjqPausedTriggerGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByExample(XjqPausedTriggerGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int deleteByPrimaryKey(XjqPausedTriggerGrpsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insert(XjqPausedTriggerGrpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int insertSelective(XjqPausedTriggerGrpsKey record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    List<XjqPausedTriggerGrpsKey> selectByExample(XjqPausedTriggerGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") XjqPausedTriggerGrpsKey record, @Param("example") XjqPausedTriggerGrpsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_PAUSED_TRIGGER_GRPS
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    int updateByExample(@Param("record") XjqPausedTriggerGrpsKey record, @Param("example") XjqPausedTriggerGrpsExample example);
}