package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.XjqTriggerLog;
import com.cn.interfacedocument.entity.XjqTriggerLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XjqTriggerLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(XjqTriggerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(XjqTriggerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(XjqTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(XjqTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<XjqTriggerLog> selectByExample(XjqTriggerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    XjqTriggerLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") XjqTriggerLog record, @Param("example") XjqTriggerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") XjqTriggerLog record, @Param("example") XjqTriggerLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(XjqTriggerLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(XjqTriggerLog record);
}