package com.cn.interfacedocument.dao;

import com.cn.interfacedocument.entity.XjqTriggerLogglue;
import com.cn.interfacedocument.entity.XjqTriggerLogglueExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface XjqTriggerLogglueMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int countByExample(XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByExample(XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insert(XjqTriggerLogglue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int insertSelective(XjqTriggerLogglue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<XjqTriggerLogglue> selectByExampleWithBLOBs(XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    List<XjqTriggerLogglue> selectByExample(XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    XjqTriggerLogglue selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleSelective(@Param("record") XjqTriggerLogglue record, @Param("example") XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") XjqTriggerLogglue record, @Param("example") XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByExample(@Param("record") XjqTriggerLogglue record, @Param("example") XjqTriggerLogglueExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeySelective(XjqTriggerLogglue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(XjqTriggerLogglue record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table XJQ_TRIGGER_LOGGLUE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    int updateByPrimaryKey(XjqTriggerLogglue record);
}