package com.cn.interfacedocument.entity;

public class AdjustBook {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.CASE_NO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String caseNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.CON_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String conSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.DAY
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String day;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.MONTH
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String month;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.PRO_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String proSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.READP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String readp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.REP_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String repSign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.YEAR
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String year;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long lawCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.SUC_OR_FAIL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String sucOrFail;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.PRO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Boolean pro;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ADJUST_BOOK.REP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Boolean rep;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.ID
     *
     * @return the value of ADJUST_BOOK.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.ID
     *
     * @param id the value for ADJUST_BOOK.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.NAME
     *
     * @return the value of ADJUST_BOOK.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.NAME
     *
     * @param name the value for ADJUST_BOOK.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.CASE_NO
     *
     * @return the value of ADJUST_BOOK.CASE_NO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getCaseNo() {
        return caseNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.CASE_NO
     *
     * @param caseNo the value for ADJUST_BOOK.CASE_NO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCaseNo(String caseNo) {
        this.caseNo = caseNo == null ? null : caseNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.CON_SIGN
     *
     * @return the value of ADJUST_BOOK.CON_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getConSign() {
        return conSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.CON_SIGN
     *
     * @param conSign the value for ADJUST_BOOK.CON_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setConSign(String conSign) {
        this.conSign = conSign == null ? null : conSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.DAY
     *
     * @return the value of ADJUST_BOOK.DAY
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getDay() {
        return day;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.DAY
     *
     * @param day the value for ADJUST_BOOK.DAY
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setDay(String day) {
        this.day = day == null ? null : day.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.EXTEND
     *
     * @return the value of ADJUST_BOOK.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.EXTEND
     *
     * @param extend the value for ADJUST_BOOK.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.MONTH
     *
     * @return the value of ADJUST_BOOK.MONTH
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getMonth() {
        return month;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.MONTH
     *
     * @param month the value for ADJUST_BOOK.MONTH
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setMonth(String month) {
        this.month = month == null ? null : month.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.ORG_NAME
     *
     * @return the value of ADJUST_BOOK.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.ORG_NAME
     *
     * @param orgName the value for ADJUST_BOOK.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.PRO_SIGN
     *
     * @return the value of ADJUST_BOOK.PRO_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getProSign() {
        return proSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.PRO_SIGN
     *
     * @param proSign the value for ADJUST_BOOK.PRO_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setProSign(String proSign) {
        this.proSign = proSign == null ? null : proSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.READP
     *
     * @return the value of ADJUST_BOOK.READP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getReadp() {
        return readp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.READP
     *
     * @param readp the value for ADJUST_BOOK.READP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setReadp(String readp) {
        this.readp = readp == null ? null : readp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.REP_SIGN
     *
     * @return the value of ADJUST_BOOK.REP_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getRepSign() {
        return repSign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.REP_SIGN
     *
     * @param repSign the value for ADJUST_BOOK.REP_SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setRepSign(String repSign) {
        this.repSign = repSign == null ? null : repSign.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.YEAR
     *
     * @return the value of ADJUST_BOOK.YEAR
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.YEAR
     *
     * @param year the value for ADJUST_BOOK.YEAR
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setYear(String year) {
        this.year = year == null ? null : year.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.LAW_CASE_ID
     *
     * @return the value of ADJUST_BOOK.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getLawCaseId() {
        return lawCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.LAW_CASE_ID
     *
     * @param lawCaseId the value for ADJUST_BOOK.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setLawCaseId(Long lawCaseId) {
        this.lawCaseId = lawCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.SUC_OR_FAIL
     *
     * @return the value of ADJUST_BOOK.SUC_OR_FAIL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getSucOrFail() {
        return sucOrFail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.SUC_OR_FAIL
     *
     * @param sucOrFail the value for ADJUST_BOOK.SUC_OR_FAIL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setSucOrFail(String sucOrFail) {
        this.sucOrFail = sucOrFail == null ? null : sucOrFail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.PRO
     *
     * @return the value of ADJUST_BOOK.PRO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Boolean getPro() {
        return pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.PRO
     *
     * @param pro the value for ADJUST_BOOK.PRO
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setPro(Boolean pro) {
        this.pro = pro;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ADJUST_BOOK.REP
     *
     * @return the value of ADJUST_BOOK.REP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Boolean getRep() {
        return rep;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ADJUST_BOOK.REP
     *
     * @param rep the value for ADJUST_BOOK.REP
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setRep(Boolean rep) {
        this.rep = rep;
    }
}