package com.cn.interfacedocument.entity;

public class Areas {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String code;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.SNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String sname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.LNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String lname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Integer level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.PARENT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String parentCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.CANTON_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Integer cantonFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.SHOW_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Integer showFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column AREAS.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.CODE
     *
     * @return the value of AREAS.CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.CODE
     *
     * @param code the value for AREAS.CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCode(String code) {
        this.code = code == null ? null : code.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.SNAME
     *
     * @return the value of AREAS.SNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getSname() {
        return sname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.SNAME
     *
     * @param sname the value for AREAS.SNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setSname(String sname) {
        this.sname = sname == null ? null : sname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.LNAME
     *
     * @return the value of AREAS.LNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getLname() {
        return lname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.LNAME
     *
     * @param lname the value for AREAS.LNAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setLname(String lname) {
        this.lname = lname == null ? null : lname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.LEVEL
     *
     * @return the value of AREAS.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Integer getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.LEVEL
     *
     * @param level the value for AREAS.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setLevel(Integer level) {
        this.level = level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.PARENT_CODE
     *
     * @return the value of AREAS.PARENT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.PARENT_CODE
     *
     * @param parentCode the value for AREAS.PARENT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setParentCode(String parentCode) {
        this.parentCode = parentCode == null ? null : parentCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.CANTON_FLAG
     *
     * @return the value of AREAS.CANTON_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Integer getCantonFlag() {
        return cantonFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.CANTON_FLAG
     *
     * @param cantonFlag the value for AREAS.CANTON_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCantonFlag(Integer cantonFlag) {
        this.cantonFlag = cantonFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.SHOW_FLAG
     *
     * @return the value of AREAS.SHOW_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Integer getShowFlag() {
        return showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.SHOW_FLAG
     *
     * @param showFlag the value for AREAS.SHOW_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setShowFlag(Integer showFlag) {
        this.showFlag = showFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column AREAS.NAME
     *
     * @return the value of AREAS.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column AREAS.NAME
     *
     * @param name the value for AREAS.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}