package com.cn.interfacedocument.entity;

import java.util.Date;

public class CommonProblem {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_PROBLEM.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_PROBLEM.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_PROBLEM.PROBLEM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String problem;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_PROBLEM.REPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String reply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COMMON_PROBLEM.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PROBLEM.ID
     *
     * @return the value of COMMON_PROBLEM.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PROBLEM.ID
     *
     * @param id the value for COMMON_PROBLEM.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PROBLEM.NAME
     *
     * @return the value of COMMON_PROBLEM.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PROBLEM.NAME
     *
     * @param name the value for COMMON_PROBLEM.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PROBLEM.PROBLEM
     *
     * @return the value of COMMON_PROBLEM.PROBLEM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getProblem() {
        return problem;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PROBLEM.PROBLEM
     *
     * @param problem the value for COMMON_PROBLEM.PROBLEM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setProblem(String problem) {
        this.problem = problem == null ? null : problem.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PROBLEM.REPLY
     *
     * @return the value of COMMON_PROBLEM.REPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getReply() {
        return reply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PROBLEM.REPLY
     *
     * @param reply the value for COMMON_PROBLEM.REPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setReply(String reply) {
        this.reply = reply == null ? null : reply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COMMON_PROBLEM.CREATE_DATE
     *
     * @return the value of COMMON_PROBLEM.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COMMON_PROBLEM.CREATE_DATE
     *
     * @param createDate the value for COMMON_PROBLEM.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }
}