package com.cn.interfacedocument.entity;

public class CounselorDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ABILITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String ability;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.AGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.AREA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String area;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.IS_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Integer isAuthenticate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.LEGAL_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String legalPerson;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ORG_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String registration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.SENIORITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String seniority;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long counselorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.AREA_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.EDUCATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.JOBSTART
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String jobstart;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.RESUME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String resume;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.CITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String city;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.DISTRICT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String district;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.IMG_OTHER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String imgOther;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.IMG_PHOTO
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String imgPhoto;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.IMG_POSITIVE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String imgPositive;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.IMG_QUA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String imgQua;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.PROVINCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String province;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column COUNSELOR_DETAIL.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ID
     *
     * @return the value of COUNSELOR_DETAIL.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ID
     *
     * @param id the value for COUNSELOR_DETAIL.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.NAME
     *
     * @return the value of COUNSELOR_DETAIL.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.NAME
     *
     * @param name the value for COUNSELOR_DETAIL.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ABILITY
     *
     * @return the value of COUNSELOR_DETAIL.ABILITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAbility() {
        return ability;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ABILITY
     *
     * @param ability the value for COUNSELOR_DETAIL.ABILITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAbility(String ability) {
        this.ability = ability == null ? null : ability.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ACTUAL_NAME
     *
     * @return the value of COUNSELOR_DETAIL.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ACTUAL_NAME
     *
     * @param actualName the value for COUNSELOR_DETAIL.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setActualName(String actualName) {
        this.actualName = actualName == null ? null : actualName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ADDRESS
     *
     * @return the value of COUNSELOR_DETAIL.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ADDRESS
     *
     * @param address the value for COUNSELOR_DETAIL.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.AGE
     *
     * @return the value of COUNSELOR_DETAIL.AGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.AGE
     *
     * @param age the value for COUNSELOR_DETAIL.AGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAge(String age) {
        this.age = age == null ? null : age.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.AREA
     *
     * @return the value of COUNSELOR_DETAIL.AREA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getArea() {
        return area;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.AREA
     *
     * @param area the value for COUNSELOR_DETAIL.AREA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setArea(String area) {
        this.area = area == null ? null : area.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.BIRTH
     *
     * @return the value of COUNSELOR_DETAIL.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.BIRTH
     *
     * @param birth the value for COUNSELOR_DETAIL.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.COMPANY_NAME
     *
     * @return the value of COUNSELOR_DETAIL.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.COMPANY_NAME
     *
     * @param companyName the value for COUNSELOR_DETAIL.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ID_CARD
     *
     * @return the value of COUNSELOR_DETAIL.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ID_CARD
     *
     * @param idCard the value for COUNSELOR_DETAIL.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.IS_AUTHENTICATE
     *
     * @return the value of COUNSELOR_DETAIL.IS_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Integer getIsAuthenticate() {
        return isAuthenticate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.IS_AUTHENTICATE
     *
     * @param isAuthenticate the value for COUNSELOR_DETAIL.IS_AUTHENTICATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIsAuthenticate(Integer isAuthenticate) {
        this.isAuthenticate = isAuthenticate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.LEGAL_PERSON
     *
     * @return the value of COUNSELOR_DETAIL.LEGAL_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getLegalPerson() {
        return legalPerson;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.LEGAL_PERSON
     *
     * @param legalPerson the value for COUNSELOR_DETAIL.LEGAL_PERSON
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLegalPerson(String legalPerson) {
        this.legalPerson = legalPerson == null ? null : legalPerson.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ORG_CODE
     *
     * @return the value of COUNSELOR_DETAIL.ORG_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgCode() {
        return orgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ORG_CODE
     *
     * @param orgCode the value for COUNSELOR_DETAIL.ORG_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgCode(String orgCode) {
        this.orgCode = orgCode == null ? null : orgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ORG_NAME
     *
     * @return the value of COUNSELOR_DETAIL.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ORG_NAME
     *
     * @param orgName the value for COUNSELOR_DETAIL.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ORG_NATURE
     *
     * @return the value of COUNSELOR_DETAIL.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgNature() {
        return orgNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ORG_NATURE
     *
     * @param orgNature the value for COUNSELOR_DETAIL.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgNature(String orgNature) {
        this.orgNature = orgNature == null ? null : orgNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.PHONE
     *
     * @return the value of COUNSELOR_DETAIL.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.PHONE
     *
     * @param phone the value for COUNSELOR_DETAIL.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.REGISTRATION
     *
     * @return the value of COUNSELOR_DETAIL.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.REGISTRATION
     *
     * @param registration the value for COUNSELOR_DETAIL.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setRegistration(String registration) {
        this.registration = registration == null ? null : registration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.SENIORITY
     *
     * @return the value of COUNSELOR_DETAIL.SENIORITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getSeniority() {
        return seniority;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.SENIORITY
     *
     * @param seniority the value for COUNSELOR_DETAIL.SENIORITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSeniority(String seniority) {
        this.seniority = seniority == null ? null : seniority.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.SEX
     *
     * @return the value of COUNSELOR_DETAIL.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.SEX
     *
     * @param sex the value for COUNSELOR_DETAIL.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.COUNSELOR_ID
     *
     * @return the value of COUNSELOR_DETAIL.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getCounselorId() {
        return counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.COUNSELOR_ID
     *
     * @param counselorId the value for COUNSELOR_DETAIL.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCounselorId(Long counselorId) {
        this.counselorId = counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.NATION
     *
     * @return the value of COUNSELOR_DETAIL.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.NATION
     *
     * @param nation the value for COUNSELOR_DETAIL.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.AREA_ID
     *
     * @return the value of COUNSELOR_DETAIL.AREA_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.AREA_ID
     *
     * @param areaId the value for COUNSELOR_DETAIL.AREA_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.EDUCATION
     *
     * @return the value of COUNSELOR_DETAIL.EDUCATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getEducation() {
        return education;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.EDUCATION
     *
     * @param education the value for COUNSELOR_DETAIL.EDUCATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setEducation(String education) {
        this.education = education == null ? null : education.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.JOB
     *
     * @return the value of COUNSELOR_DETAIL.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.JOB
     *
     * @param job the value for COUNSELOR_DETAIL.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.JOBSTART
     *
     * @return the value of COUNSELOR_DETAIL.JOBSTART
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getJobstart() {
        return jobstart;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.JOBSTART
     *
     * @param jobstart the value for COUNSELOR_DETAIL.JOBSTART
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setJobstart(String jobstart) {
        this.jobstart = jobstart == null ? null : jobstart.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.RESUME
     *
     * @return the value of COUNSELOR_DETAIL.RESUME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getResume() {
        return resume;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.RESUME
     *
     * @param resume the value for COUNSELOR_DETAIL.RESUME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setResume(String resume) {
        this.resume = resume == null ? null : resume.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.ROLE
     *
     * @return the value of COUNSELOR_DETAIL.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.ROLE
     *
     * @param role the value for COUNSELOR_DETAIL.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.CITY
     *
     * @return the value of COUNSELOR_DETAIL.CITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.CITY
     *
     * @param city the value for COUNSELOR_DETAIL.CITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.DISTRICT
     *
     * @return the value of COUNSELOR_DETAIL.DISTRICT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.DISTRICT
     *
     * @param district the value for COUNSELOR_DETAIL.DISTRICT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setDistrict(String district) {
        this.district = district == null ? null : district.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.IMG_OTHER
     *
     * @return the value of COUNSELOR_DETAIL.IMG_OTHER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getImgOther() {
        return imgOther;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.IMG_OTHER
     *
     * @param imgOther the value for COUNSELOR_DETAIL.IMG_OTHER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setImgOther(String imgOther) {
        this.imgOther = imgOther == null ? null : imgOther.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.IMG_PHOTO
     *
     * @return the value of COUNSELOR_DETAIL.IMG_PHOTO
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getImgPhoto() {
        return imgPhoto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.IMG_PHOTO
     *
     * @param imgPhoto the value for COUNSELOR_DETAIL.IMG_PHOTO
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setImgPhoto(String imgPhoto) {
        this.imgPhoto = imgPhoto == null ? null : imgPhoto.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.IMG_POSITIVE
     *
     * @return the value of COUNSELOR_DETAIL.IMG_POSITIVE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getImgPositive() {
        return imgPositive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.IMG_POSITIVE
     *
     * @param imgPositive the value for COUNSELOR_DETAIL.IMG_POSITIVE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setImgPositive(String imgPositive) {
        this.imgPositive = imgPositive == null ? null : imgPositive.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.IMG_QUA
     *
     * @return the value of COUNSELOR_DETAIL.IMG_QUA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getImgQua() {
        return imgQua;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.IMG_QUA
     *
     * @param imgQua the value for COUNSELOR_DETAIL.IMG_QUA
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setImgQua(String imgQua) {
        this.imgQua = imgQua == null ? null : imgQua.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.PROVINCE
     *
     * @return the value of COUNSELOR_DETAIL.PROVINCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.PROVINCE
     *
     * @param province the value for COUNSELOR_DETAIL.PROVINCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setProvince(String province) {
        this.province = province == null ? null : province.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column COUNSELOR_DETAIL.TYPE
     *
     * @return the value of COUNSELOR_DETAIL.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column COUNSELOR_DETAIL.TYPE
     *
     * @param type the value for COUNSELOR_DETAIL.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}