package com.cn.interfacedocument.entity;

import java.util.Date;

public class DisputesMessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.AUTO_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String autoSessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.CASE_CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String caseCause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_MESSAGE.MESSAGES
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String messages;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.ID
     *
     * @return the value of DISPUTES_MESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.ID
     *
     * @param id the value for DISPUTES_MESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.AUTO_SESSION_ID
     *
     * @return the value of DISPUTES_MESSAGE.AUTO_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getAutoSessionId() {
        return autoSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.AUTO_SESSION_ID
     *
     * @param autoSessionId the value for DISPUTES_MESSAGE.AUTO_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setAutoSessionId(String autoSessionId) {
        this.autoSessionId = autoSessionId == null ? null : autoSessionId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.CASE_CAUSE
     *
     * @return the value of DISPUTES_MESSAGE.CASE_CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getCaseCause() {
        return caseCause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.CASE_CAUSE
     *
     * @param caseCause the value for DISPUTES_MESSAGE.CASE_CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCaseCause(String caseCause) {
        this.caseCause = caseCause == null ? null : caseCause.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.CREATE_TIME
     *
     * @return the value of DISPUTES_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.CREATE_TIME
     *
     * @param createTime the value for DISPUTES_MESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.UPDATE_TIME
     *
     * @return the value of DISPUTES_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.UPDATE_TIME
     *
     * @param updateTime the value for DISPUTES_MESSAGE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_MESSAGE.MESSAGES
     *
     * @return the value of DISPUTES_MESSAGE.MESSAGES
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getMessages() {
        return messages;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_MESSAGE.MESSAGES
     *
     * @param messages the value for DISPUTES_MESSAGE.MESSAGES
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setMessages(String messages) {
        this.messages = messages == null ? null : messages.trim();
    }
}