package com.cn.interfacedocument.entity;

import java.util.Date;

public class DisputesSession {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.CLAIM_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date claimTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.ISSWITCH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String isswitch;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.LATEST_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date latestTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.REPORT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long report;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.STATUS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.VALID_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date validTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.CLIENT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long clientId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long counselorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.DISPUTES_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long disputesId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SESSION.OPIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String opin;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.ID
     *
     * @return the value of DISPUTES_SESSION.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.ID
     *
     * @param id the value for DISPUTES_SESSION.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.NAME
     *
     * @return the value of DISPUTES_SESSION.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.NAME
     *
     * @param name the value for DISPUTES_SESSION.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.CLAIM_TIME
     *
     * @return the value of DISPUTES_SESSION.CLAIM_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getClaimTime() {
        return claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.CLAIM_TIME
     *
     * @param claimTime the value for DISPUTES_SESSION.CLAIM_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setClaimTime(Date claimTime) {
        this.claimTime = claimTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.ISSWITCH
     *
     * @return the value of DISPUTES_SESSION.ISSWITCH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIsswitch() {
        return isswitch;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.ISSWITCH
     *
     * @param isswitch the value for DISPUTES_SESSION.ISSWITCH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIsswitch(String isswitch) {
        this.isswitch = isswitch == null ? null : isswitch.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.LATEST_TIME
     *
     * @return the value of DISPUTES_SESSION.LATEST_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getLatestTime() {
        return latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.LATEST_TIME
     *
     * @param latestTime the value for DISPUTES_SESSION.LATEST_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLatestTime(Date latestTime) {
        this.latestTime = latestTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.REPORT
     *
     * @return the value of DISPUTES_SESSION.REPORT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getReport() {
        return report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.REPORT
     *
     * @param report the value for DISPUTES_SESSION.REPORT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setReport(Long report) {
        this.report = report;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.STATUS
     *
     * @return the value of DISPUTES_SESSION.STATUS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.STATUS
     *
     * @param status the value for DISPUTES_SESSION.STATUS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.VALID_TIME
     *
     * @return the value of DISPUTES_SESSION.VALID_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getValidTime() {
        return validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.VALID_TIME
     *
     * @param validTime the value for DISPUTES_SESSION.VALID_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setValidTime(Date validTime) {
        this.validTime = validTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.CLIENT_ID
     *
     * @return the value of DISPUTES_SESSION.CLIENT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getClientId() {
        return clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.CLIENT_ID
     *
     * @param clientId the value for DISPUTES_SESSION.CLIENT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setClientId(Long clientId) {
        this.clientId = clientId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.COUNSELOR_ID
     *
     * @return the value of DISPUTES_SESSION.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getCounselorId() {
        return counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.COUNSELOR_ID
     *
     * @param counselorId the value for DISPUTES_SESSION.COUNSELOR_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCounselorId(Long counselorId) {
        this.counselorId = counselorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.DISPUTES_ID
     *
     * @return the value of DISPUTES_SESSION.DISPUTES_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getDisputesId() {
        return disputesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.DISPUTES_ID
     *
     * @param disputesId the value for DISPUTES_SESSION.DISPUTES_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setDisputesId(Long disputesId) {
        this.disputesId = disputesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.CREATE_TIME
     *
     * @return the value of DISPUTES_SESSION.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.CREATE_TIME
     *
     * @param createTime the value for DISPUTES_SESSION.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.UPDATE_TIME
     *
     * @return the value of DISPUTES_SESSION.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.UPDATE_TIME
     *
     * @param updateTime the value for DISPUTES_SESSION.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SESSION.OPIN
     *
     * @return the value of DISPUTES_SESSION.OPIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOpin() {
        return opin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SESSION.OPIN
     *
     * @param opin the value for DISPUTES_SESSION.OPIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOpin(String opin) {
        this.opin = opin == null ? null : opin.trim();
    }
}