package com.cn.interfacedocument.entity;

import java.util.Date;

public class DisputesScore {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.SATISFIED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String satisfied;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.DISPUTES_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long disputesSessionId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column DISPUTES_SCORE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.ID
     *
     * @return the value of DISPUTES_SCORE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.ID
     *
     * @param id the value for DISPUTES_SCORE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.NAME
     *
     * @return the value of DISPUTES_SCORE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.NAME
     *
     * @param name the value for DISPUTES_SCORE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.LEVEL
     *
     * @return the value of DISPUTES_SCORE.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.LEVEL
     *
     * @param level the value for DISPUTES_SCORE.LEVEL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.SATISFIED
     *
     * @return the value of DISPUTES_SCORE.SATISFIED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getSatisfied() {
        return satisfied;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.SATISFIED
     *
     * @param satisfied the value for DISPUTES_SCORE.SATISFIED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSatisfied(String satisfied) {
        this.satisfied = satisfied == null ? null : satisfied.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.DISPUTES_SESSION_ID
     *
     * @return the value of DISPUTES_SCORE.DISPUTES_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getDisputesSessionId() {
        return disputesSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.DISPUTES_SESSION_ID
     *
     * @param disputesSessionId the value for DISPUTES_SCORE.DISPUTES_SESSION_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setDisputesSessionId(Long disputesSessionId) {
        this.disputesSessionId = disputesSessionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.CREATE_TIME
     *
     * @return the value of DISPUTES_SCORE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.CREATE_TIME
     *
     * @param createTime the value for DISPUTES_SCORE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column DISPUTES_SCORE.UPDATE_TIME
     *
     * @return the value of DISPUTES_SCORE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column DISPUTES_SCORE.UPDATE_TIME
     *
     * @param updateTime the value for DISPUTES_SCORE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}