package com.cn.interfacedocument.entity;

import java.math.BigDecimal;
import java.util.Date;

public class LawCaseAttachment {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CATEGORYB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String categoryb;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CATEGORYM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String categorym;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CATEGORYS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String categorys;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.DEL_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String delFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long caseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.USER_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.OWNER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String owner;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.COUNSELOR_AND_MEDIATORS_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long counselorAndMediatorsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.PERSONNEL_IDS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String personnelIds;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Integer sign;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String meettingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long personnelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.SOURCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.PERFORMANCE_TIME_LIMIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date performanceTimeLimit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.WAY_OF_FULFILLMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String wayOfFulfillment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.AMOUNT_INVOLVED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private BigDecimal amountInvolved;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.PLACE_OF_PERFORMANCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String placeOfPerformance;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.CONTENT_AGREEMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String contentAgreement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_CASE_ATTACHMENT.HASHCODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String hashcode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.ID
     *
     * @param id the value for LAW_CASE_ATTACHMENT.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.NAME
     *
     * @return the value of LAW_CASE_ATTACHMENT.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.NAME
     *
     * @param name the value for LAW_CASE_ATTACHMENT.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CATEGORYB
     *
     * @return the value of LAW_CASE_ATTACHMENT.CATEGORYB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCategoryb() {
        return categoryb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CATEGORYB
     *
     * @param categoryb the value for LAW_CASE_ATTACHMENT.CATEGORYB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCategoryb(String categoryb) {
        this.categoryb = categoryb == null ? null : categoryb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CATEGORYM
     *
     * @return the value of LAW_CASE_ATTACHMENT.CATEGORYM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCategorym() {
        return categorym;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CATEGORYM
     *
     * @param categorym the value for LAW_CASE_ATTACHMENT.CATEGORYM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCategorym(String categorym) {
        this.categorym = categorym == null ? null : categorym.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CATEGORYS
     *
     * @return the value of LAW_CASE_ATTACHMENT.CATEGORYS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCategorys() {
        return categorys;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CATEGORYS
     *
     * @param categorys the value for LAW_CASE_ATTACHMENT.CATEGORYS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCategorys(String categorys) {
        this.categorys = categorys == null ? null : categorys.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CONTENT
     *
     * @return the value of LAW_CASE_ATTACHMENT.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CONTENT
     *
     * @param content the value for LAW_CASE_ATTACHMENT.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.DEL_FLAG
     *
     * @return the value of LAW_CASE_ATTACHMENT.DEL_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getDelFlag() {
        return delFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.DEL_FLAG
     *
     * @param delFlag the value for LAW_CASE_ATTACHMENT.DEL_FLAG
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setDelFlag(String delFlag) {
        this.delFlag = delFlag == null ? null : delFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.TYPE
     *
     * @return the value of LAW_CASE_ATTACHMENT.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.TYPE
     *
     * @param type the value for LAW_CASE_ATTACHMENT.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.URL
     *
     * @return the value of LAW_CASE_ATTACHMENT.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.URL
     *
     * @param url the value for LAW_CASE_ATTACHMENT.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CASE_ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getCaseId() {
        return caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CASE_ID
     *
     * @param caseId the value for LAW_CASE_ATTACHMENT.CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCaseId(Long caseId) {
        this.caseId = caseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.USER_ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.USER_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.USER_ID
     *
     * @param userId the value for LAW_CASE_ATTACHMENT.USER_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.OWNER
     *
     * @return the value of LAW_CASE_ATTACHMENT.OWNER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOwner() {
        return owner;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.OWNER
     *
     * @param owner the value for LAW_CASE_ATTACHMENT.OWNER
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOwner(String owner) {
        this.owner = owner == null ? null : owner.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CREATE_TIME
     *
     * @return the value of LAW_CASE_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CREATE_TIME
     *
     * @param createTime the value for LAW_CASE_ATTACHMENT.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.UPDATE_TIME
     *
     * @return the value of LAW_CASE_ATTACHMENT.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.UPDATE_TIME
     *
     * @param updateTime the value for LAW_CASE_ATTACHMENT.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.COUNSELOR_AND_MEDIATORS_ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.COUNSELOR_AND_MEDIATORS_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getCounselorAndMediatorsId() {
        return counselorAndMediatorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.COUNSELOR_AND_MEDIATORS_ID
     *
     * @param counselorAndMediatorsId the value for LAW_CASE_ATTACHMENT.COUNSELOR_AND_MEDIATORS_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCounselorAndMediatorsId(Long counselorAndMediatorsId) {
        this.counselorAndMediatorsId = counselorAndMediatorsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.ROLE
     *
     * @return the value of LAW_CASE_ATTACHMENT.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.ROLE
     *
     * @param role the value for LAW_CASE_ATTACHMENT.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setRole(String role) {
        this.role = role == null ? null : role.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.PERSONNEL_IDS
     *
     * @return the value of LAW_CASE_ATTACHMENT.PERSONNEL_IDS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPersonnelIds() {
        return personnelIds;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.PERSONNEL_IDS
     *
     * @param personnelIds the value for LAW_CASE_ATTACHMENT.PERSONNEL_IDS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPersonnelIds(String personnelIds) {
        this.personnelIds = personnelIds == null ? null : personnelIds.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.SIGN
     *
     * @return the value of LAW_CASE_ATTACHMENT.SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Integer getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.SIGN
     *
     * @param sign the value for LAW_CASE_ATTACHMENT.SIGN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSign(Integer sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.MEETTING_ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getMeettingId() {
        return meettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.MEETTING_ID
     *
     * @param meettingId the value for LAW_CASE_ATTACHMENT.MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setMeettingId(String meettingId) {
        this.meettingId = meettingId == null ? null : meettingId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.PERSONNEL_ID
     *
     * @return the value of LAW_CASE_ATTACHMENT.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getPersonnelId() {
        return personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.PERSONNEL_ID
     *
     * @param personnelId the value for LAW_CASE_ATTACHMENT.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPersonnelId(Long personnelId) {
        this.personnelId = personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.SOURCE
     *
     * @return the value of LAW_CASE_ATTACHMENT.SOURCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.SOURCE
     *
     * @param source the value for LAW_CASE_ATTACHMENT.SOURCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.PERFORMANCE_TIME_LIMIT
     *
     * @return the value of LAW_CASE_ATTACHMENT.PERFORMANCE_TIME_LIMIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getPerformanceTimeLimit() {
        return performanceTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.PERFORMANCE_TIME_LIMIT
     *
     * @param performanceTimeLimit the value for LAW_CASE_ATTACHMENT.PERFORMANCE_TIME_LIMIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPerformanceTimeLimit(Date performanceTimeLimit) {
        this.performanceTimeLimit = performanceTimeLimit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.WAY_OF_FULFILLMENT
     *
     * @return the value of LAW_CASE_ATTACHMENT.WAY_OF_FULFILLMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getWayOfFulfillment() {
        return wayOfFulfillment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.WAY_OF_FULFILLMENT
     *
     * @param wayOfFulfillment the value for LAW_CASE_ATTACHMENT.WAY_OF_FULFILLMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setWayOfFulfillment(String wayOfFulfillment) {
        this.wayOfFulfillment = wayOfFulfillment == null ? null : wayOfFulfillment.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.AMOUNT_INVOLVED
     *
     * @return the value of LAW_CASE_ATTACHMENT.AMOUNT_INVOLVED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public BigDecimal getAmountInvolved() {
        return amountInvolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.AMOUNT_INVOLVED
     *
     * @param amountInvolved the value for LAW_CASE_ATTACHMENT.AMOUNT_INVOLVED
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAmountInvolved(BigDecimal amountInvolved) {
        this.amountInvolved = amountInvolved;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.PLACE_OF_PERFORMANCE
     *
     * @return the value of LAW_CASE_ATTACHMENT.PLACE_OF_PERFORMANCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPlaceOfPerformance() {
        return placeOfPerformance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.PLACE_OF_PERFORMANCE
     *
     * @param placeOfPerformance the value for LAW_CASE_ATTACHMENT.PLACE_OF_PERFORMANCE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPlaceOfPerformance(String placeOfPerformance) {
        this.placeOfPerformance = placeOfPerformance == null ? null : placeOfPerformance.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.CONTENT_AGREEMENT
     *
     * @return the value of LAW_CASE_ATTACHMENT.CONTENT_AGREEMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getContentAgreement() {
        return contentAgreement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.CONTENT_AGREEMENT
     *
     * @param contentAgreement the value for LAW_CASE_ATTACHMENT.CONTENT_AGREEMENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setContentAgreement(String contentAgreement) {
        this.contentAgreement = contentAgreement == null ? null : contentAgreement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_CASE_ATTACHMENT.HASHCODE
     *
     * @return the value of LAW_CASE_ATTACHMENT.HASHCODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getHashcode() {
        return hashcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_CASE_ATTACHMENT.HASHCODE
     *
     * @param hashcode the value for LAW_CASE_ATTACHMENT.HASHCODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setHashcode(String hashcode) {
        this.hashcode = hashcode == null ? null : hashcode.trim();
    }
}