package com.cn.interfacedocument.entity;

import java.util.Date;

public class LawSuitPerson {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.BANK_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String bankCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.BANK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String bankName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String birth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.CERTIFICATE_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String certificateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.CORPORATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String corporation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.COUNTRY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String country;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.COUNTRY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String countryCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ELECTRONIC
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String electronic;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ENTERPRISE_PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String enterprisePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String extend;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.IDENTITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String identity;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.IDENTITY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String identityCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String job;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.JOB_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String jobCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String nation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.NATION_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String nationCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ORDERS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Integer orders;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgNature;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ORG_NATURE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgNatureCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.POST_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String postCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.PROCREDIT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String procreditCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String registration;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.RESIDENT_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String residentAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Integer role;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.type
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.LAWSUIT_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long lawsuitDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.AREAS_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String areasCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.USER_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long userDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.LAW_SUIT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long lawSuitId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.DOC_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String docAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.AGENT_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String agentType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.AGENT_LICENSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String agentLicense;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_PERSON.AGENT_LAW_FIRM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String agentLawFirm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ID
     *
     * @return the value of LAW_SUIT_PERSON.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ID
     *
     * @param id the value for LAW_SUIT_PERSON.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.NAME
     *
     * @return the value of LAW_SUIT_PERSON.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.NAME
     *
     * @param name the value for LAW_SUIT_PERSON.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ACTUAL_NAME
     *
     * @return the value of LAW_SUIT_PERSON.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ACTUAL_NAME
     *
     * @param actualName the value for LAW_SUIT_PERSON.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setActualName(String actualName) {
        this.actualName = actualName == null ? null : actualName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ADDRESS
     *
     * @return the value of LAW_SUIT_PERSON.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ADDRESS
     *
     * @param address the value for LAW_SUIT_PERSON.ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.BANK_CODE
     *
     * @return the value of LAW_SUIT_PERSON.BANK_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getBankCode() {
        return bankCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.BANK_CODE
     *
     * @param bankCode the value for LAW_SUIT_PERSON.BANK_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setBankCode(String bankCode) {
        this.bankCode = bankCode == null ? null : bankCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.BANK_NAME
     *
     * @return the value of LAW_SUIT_PERSON.BANK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getBankName() {
        return bankName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.BANK_NAME
     *
     * @param bankName the value for LAW_SUIT_PERSON.BANK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setBankName(String bankName) {
        this.bankName = bankName == null ? null : bankName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.BIRTH
     *
     * @return the value of LAW_SUIT_PERSON.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.BIRTH
     *
     * @param birth the value for LAW_SUIT_PERSON.BIRTH
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setBirth(String birth) {
        this.birth = birth == null ? null : birth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.CERTIFICATE_TYPE
     *
     * @return the value of LAW_SUIT_PERSON.CERTIFICATE_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCertificateType() {
        return certificateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.CERTIFICATE_TYPE
     *
     * @param certificateType the value for LAW_SUIT_PERSON.CERTIFICATE_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCertificateType(String certificateType) {
        this.certificateType = certificateType == null ? null : certificateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.COMPANY_NAME
     *
     * @return the value of LAW_SUIT_PERSON.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.COMPANY_NAME
     *
     * @param companyName the value for LAW_SUIT_PERSON.COMPANY_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.CORPORATION
     *
     * @return the value of LAW_SUIT_PERSON.CORPORATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCorporation() {
        return corporation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.CORPORATION
     *
     * @param corporation the value for LAW_SUIT_PERSON.CORPORATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCorporation(String corporation) {
        this.corporation = corporation == null ? null : corporation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.COUNTRY
     *
     * @return the value of LAW_SUIT_PERSON.COUNTRY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.COUNTRY
     *
     * @param country the value for LAW_SUIT_PERSON.COUNTRY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.COUNTRY_CODE
     *
     * @return the value of LAW_SUIT_PERSON.COUNTRY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCountryCode() {
        return countryCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.COUNTRY_CODE
     *
     * @param countryCode the value for LAW_SUIT_PERSON.COUNTRY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCountryCode(String countryCode) {
        this.countryCode = countryCode == null ? null : countryCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.CREATE_TIME
     *
     * @return the value of LAW_SUIT_PERSON.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.CREATE_TIME
     *
     * @param createTime the value for LAW_SUIT_PERSON.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ELECTRONIC
     *
     * @return the value of LAW_SUIT_PERSON.ELECTRONIC
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getElectronic() {
        return electronic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ELECTRONIC
     *
     * @param electronic the value for LAW_SUIT_PERSON.ELECTRONIC
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setElectronic(String electronic) {
        this.electronic = electronic == null ? null : electronic.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.EMAIL
     *
     * @return the value of LAW_SUIT_PERSON.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.EMAIL
     *
     * @param email the value for LAW_SUIT_PERSON.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ENTERPRISE_PHONE
     *
     * @return the value of LAW_SUIT_PERSON.ENTERPRISE_PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getEnterprisePhone() {
        return enterprisePhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ENTERPRISE_PHONE
     *
     * @param enterprisePhone the value for LAW_SUIT_PERSON.ENTERPRISE_PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setEnterprisePhone(String enterprisePhone) {
        this.enterprisePhone = enterprisePhone == null ? null : enterprisePhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.EXTEND
     *
     * @return the value of LAW_SUIT_PERSON.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getExtend() {
        return extend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.EXTEND
     *
     * @param extend the value for LAW_SUIT_PERSON.EXTEND
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setExtend(String extend) {
        this.extend = extend == null ? null : extend.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ID_CARD
     *
     * @return the value of LAW_SUIT_PERSON.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ID_CARD
     *
     * @param idCard the value for LAW_SUIT_PERSON.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.IDENTITY
     *
     * @return the value of LAW_SUIT_PERSON.IDENTITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIdentity() {
        return identity;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.IDENTITY
     *
     * @param identity the value for LAW_SUIT_PERSON.IDENTITY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIdentity(String identity) {
        this.identity = identity == null ? null : identity.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.IDENTITY_CODE
     *
     * @return the value of LAW_SUIT_PERSON.IDENTITY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIdentityCode() {
        return identityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.IDENTITY_CODE
     *
     * @param identityCode the value for LAW_SUIT_PERSON.IDENTITY_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIdentityCode(String identityCode) {
        this.identityCode = identityCode == null ? null : identityCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.JOB
     *
     * @return the value of LAW_SUIT_PERSON.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.JOB
     *
     * @param job the value for LAW_SUIT_PERSON.JOB
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setJob(String job) {
        this.job = job == null ? null : job.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.JOB_CODE
     *
     * @return the value of LAW_SUIT_PERSON.JOB_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getJobCode() {
        return jobCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.JOB_CODE
     *
     * @param jobCode the value for LAW_SUIT_PERSON.JOB_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setJobCode(String jobCode) {
        this.jobCode = jobCode == null ? null : jobCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.NATION
     *
     * @return the value of LAW_SUIT_PERSON.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getNation() {
        return nation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.NATION
     *
     * @param nation the value for LAW_SUIT_PERSON.NATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setNation(String nation) {
        this.nation = nation == null ? null : nation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.NATION_CODE
     *
     * @return the value of LAW_SUIT_PERSON.NATION_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getNationCode() {
        return nationCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.NATION_CODE
     *
     * @param nationCode the value for LAW_SUIT_PERSON.NATION_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setNationCode(String nationCode) {
        this.nationCode = nationCode == null ? null : nationCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ORDERS
     *
     * @return the value of LAW_SUIT_PERSON.ORDERS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Integer getOrders() {
        return orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ORDERS
     *
     * @param orders the value for LAW_SUIT_PERSON.ORDERS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrders(Integer orders) {
        this.orders = orders;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ORG_NAME
     *
     * @return the value of LAW_SUIT_PERSON.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ORG_NAME
     *
     * @param orgName the value for LAW_SUIT_PERSON.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ORG_NATURE
     *
     * @return the value of LAW_SUIT_PERSON.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgNature() {
        return orgNature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ORG_NATURE
     *
     * @param orgNature the value for LAW_SUIT_PERSON.ORG_NATURE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgNature(String orgNature) {
        this.orgNature = orgNature == null ? null : orgNature.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ORG_NATURE_CODE
     *
     * @return the value of LAW_SUIT_PERSON.ORG_NATURE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgNatureCode() {
        return orgNatureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ORG_NATURE_CODE
     *
     * @param orgNatureCode the value for LAW_SUIT_PERSON.ORG_NATURE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgNatureCode(String orgNatureCode) {
        this.orgNatureCode = orgNatureCode == null ? null : orgNatureCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.PHONE
     *
     * @return the value of LAW_SUIT_PERSON.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.PHONE
     *
     * @param phone the value for LAW_SUIT_PERSON.PHONE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.POST_CODE
     *
     * @return the value of LAW_SUIT_PERSON.POST_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPostCode() {
        return postCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.POST_CODE
     *
     * @param postCode the value for LAW_SUIT_PERSON.POST_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPostCode(String postCode) {
        this.postCode = postCode == null ? null : postCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.PROCREDIT_CODE
     *
     * @return the value of LAW_SUIT_PERSON.PROCREDIT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getProcreditCode() {
        return procreditCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.PROCREDIT_CODE
     *
     * @param procreditCode the value for LAW_SUIT_PERSON.PROCREDIT_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setProcreditCode(String procreditCode) {
        this.procreditCode = procreditCode == null ? null : procreditCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.REGISTRATION
     *
     * @return the value of LAW_SUIT_PERSON.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getRegistration() {
        return registration;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.REGISTRATION
     *
     * @param registration the value for LAW_SUIT_PERSON.REGISTRATION
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setRegistration(String registration) {
        this.registration = registration == null ? null : registration.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.RESIDENT_ADDRESS
     *
     * @return the value of LAW_SUIT_PERSON.RESIDENT_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getResidentAddress() {
        return residentAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.RESIDENT_ADDRESS
     *
     * @param residentAddress the value for LAW_SUIT_PERSON.RESIDENT_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setResidentAddress(String residentAddress) {
        this.residentAddress = residentAddress == null ? null : residentAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.ROLE
     *
     * @return the value of LAW_SUIT_PERSON.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Integer getRole() {
        return role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.ROLE
     *
     * @param role the value for LAW_SUIT_PERSON.ROLE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setRole(Integer role) {
        this.role = role;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.SEX
     *
     * @return the value of LAW_SUIT_PERSON.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.SEX
     *
     * @param sex the value for LAW_SUIT_PERSON.SEX
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setSex(String sex) {
        this.sex = sex == null ? null : sex.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.type
     *
     * @return the value of LAW_SUIT_PERSON.type
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.type
     *
     * @param type the value for LAW_SUIT_PERSON.type
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.UPDATE_TIME
     *
     * @return the value of LAW_SUIT_PERSON.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.UPDATE_TIME
     *
     * @param updateTime the value for LAW_SUIT_PERSON.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.LAWSUIT_DETAIL_ID
     *
     * @return the value of LAW_SUIT_PERSON.LAWSUIT_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getLawsuitDetailId() {
        return lawsuitDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.LAWSUIT_DETAIL_ID
     *
     * @param lawsuitDetailId the value for LAW_SUIT_PERSON.LAWSUIT_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLawsuitDetailId(Long lawsuitDetailId) {
        this.lawsuitDetailId = lawsuitDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.AREAS_CODE
     *
     * @return the value of LAW_SUIT_PERSON.AREAS_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAreasCode() {
        return areasCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.AREAS_CODE
     *
     * @param areasCode the value for LAW_SUIT_PERSON.AREAS_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAreasCode(String areasCode) {
        this.areasCode = areasCode == null ? null : areasCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.USER_DETAIL_ID
     *
     * @return the value of LAW_SUIT_PERSON.USER_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getUserDetailId() {
        return userDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.USER_DETAIL_ID
     *
     * @param userDetailId the value for LAW_SUIT_PERSON.USER_DETAIL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUserDetailId(Long userDetailId) {
        this.userDetailId = userDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.LAW_SUIT_ID
     *
     * @return the value of LAW_SUIT_PERSON.LAW_SUIT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getLawSuitId() {
        return lawSuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.LAW_SUIT_ID
     *
     * @param lawSuitId the value for LAW_SUIT_PERSON.LAW_SUIT_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLawSuitId(Long lawSuitId) {
        this.lawSuitId = lawSuitId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.DOC_ADDRESS
     *
     * @return the value of LAW_SUIT_PERSON.DOC_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getDocAddress() {
        return docAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.DOC_ADDRESS
     *
     * @param docAddress the value for LAW_SUIT_PERSON.DOC_ADDRESS
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setDocAddress(String docAddress) {
        this.docAddress = docAddress == null ? null : docAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.AGENT_TYPE
     *
     * @return the value of LAW_SUIT_PERSON.AGENT_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAgentType() {
        return agentType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.AGENT_TYPE
     *
     * @param agentType the value for LAW_SUIT_PERSON.AGENT_TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAgentType(String agentType) {
        this.agentType = agentType == null ? null : agentType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.AGENT_LICENSE
     *
     * @return the value of LAW_SUIT_PERSON.AGENT_LICENSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAgentLicense() {
        return agentLicense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.AGENT_LICENSE
     *
     * @param agentLicense the value for LAW_SUIT_PERSON.AGENT_LICENSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAgentLicense(String agentLicense) {
        this.agentLicense = agentLicense == null ? null : agentLicense.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_PERSON.AGENT_LAW_FIRM
     *
     * @return the value of LAW_SUIT_PERSON.AGENT_LAW_FIRM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAgentLawFirm() {
        return agentLawFirm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_PERSON.AGENT_LAW_FIRM
     *
     * @param agentLawFirm the value for LAW_SUIT_PERSON.AGENT_LAW_FIRM
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAgentLawFirm(String agentLawFirm) {
        this.agentLawFirm = agentLawFirm == null ? null : agentLawFirm.trim();
    }
}