package com.cn.interfacedocument.entity;

public class LawSuitWithBLOBs extends LawSuit {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT.APPEAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String appeal;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT.CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String cause;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT.APPEAL
     *
     * @return the value of LAW_SUIT.APPEAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getAppeal() {
        return appeal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT.APPEAL
     *
     * @param appeal the value for LAW_SUIT.APPEAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setAppeal(String appeal) {
        this.appeal = appeal == null ? null : appeal.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT.CAUSE
     *
     * @return the value of LAW_SUIT.CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getCause() {
        return cause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT.CAUSE
     *
     * @param cause the value for LAW_SUIT.CAUSE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCause(String cause) {
        this.cause = cause == null ? null : cause.trim();
    }
}