package com.cn.interfacedocument.entity;

import java.util.Date;

public class LawSuitNemessage {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.IS_FILE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Boolean isFile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.IS_READ
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Boolean isRead;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.SENDER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String sender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long lawMeettingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private Long personnelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LAW_SUIT_NEMESSAGE.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String content;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.ID
     *
     * @return the value of LAW_SUIT_NEMESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.ID
     *
     * @param id the value for LAW_SUIT_NEMESSAGE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.NAME
     *
     * @return the value of LAW_SUIT_NEMESSAGE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.NAME
     *
     * @param name the value for LAW_SUIT_NEMESSAGE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.CREATE_TIME
     *
     * @return the value of LAW_SUIT_NEMESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.CREATE_TIME
     *
     * @param createTime the value for LAW_SUIT_NEMESSAGE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.IS_FILE
     *
     * @return the value of LAW_SUIT_NEMESSAGE.IS_FILE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Boolean getIsFile() {
        return isFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.IS_FILE
     *
     * @param isFile the value for LAW_SUIT_NEMESSAGE.IS_FILE
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setIsFile(Boolean isFile) {
        this.isFile = isFile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.IS_READ
     *
     * @return the value of LAW_SUIT_NEMESSAGE.IS_READ
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Boolean getIsRead() {
        return isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.IS_READ
     *
     * @param isRead the value for LAW_SUIT_NEMESSAGE.IS_READ
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setIsRead(Boolean isRead) {
        this.isRead = isRead;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.SENDER
     *
     * @return the value of LAW_SUIT_NEMESSAGE.SENDER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getSender() {
        return sender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.SENDER
     *
     * @param sender the value for LAW_SUIT_NEMESSAGE.SENDER
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setSender(String sender) {
        this.sender = sender == null ? null : sender.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.LAW_MEETTING_ID
     *
     * @return the value of LAW_SUIT_NEMESSAGE.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getLawMeettingId() {
        return lawMeettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.LAW_MEETTING_ID
     *
     * @param lawMeettingId the value for LAW_SUIT_NEMESSAGE.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setLawMeettingId(Long lawMeettingId) {
        this.lawMeettingId = lawMeettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.PERSONNEL_ID
     *
     * @return the value of LAW_SUIT_NEMESSAGE.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public Long getPersonnelId() {
        return personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.PERSONNEL_ID
     *
     * @param personnelId the value for LAW_SUIT_NEMESSAGE.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setPersonnelId(Long personnelId) {
        this.personnelId = personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LAW_SUIT_NEMESSAGE.CONTENT
     *
     * @return the value of LAW_SUIT_NEMESSAGE.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LAW_SUIT_NEMESSAGE.CONTENT
     *
     * @param content the value for LAW_SUIT_NEMESSAGE.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }
}