package com.cn.interfacedocument.entity;

import java.util.Date;

public class OrganizationType {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.ORG_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long orgId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.ORG_CATEGORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String orgCategory;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String typeCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.TYPE_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String typeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORGANIZATION_TYPE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.ID
     *
     * @return the value of ORGANIZATION_TYPE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.ID
     *
     * @param id the value for ORGANIZATION_TYPE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.ORG_ID
     *
     * @return the value of ORGANIZATION_TYPE.ORG_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getOrgId() {
        return orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.ORG_ID
     *
     * @param orgId the value for ORGANIZATION_TYPE.ORG_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.ORG_NAME
     *
     * @return the value of ORGANIZATION_TYPE.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgName() {
        return orgName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.ORG_NAME
     *
     * @param orgName the value for ORGANIZATION_TYPE.ORG_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgName(String orgName) {
        this.orgName = orgName == null ? null : orgName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.ORG_CATEGORY
     *
     * @return the value of ORGANIZATION_TYPE.ORG_CATEGORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getOrgCategory() {
        return orgCategory;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.ORG_CATEGORY
     *
     * @param orgCategory the value for ORGANIZATION_TYPE.ORG_CATEGORY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setOrgCategory(String orgCategory) {
        this.orgCategory = orgCategory == null ? null : orgCategory.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.TYPE_CODE
     *
     * @return the value of ORGANIZATION_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getTypeCode() {
        return typeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.TYPE_CODE
     *
     * @param typeCode the value for ORGANIZATION_TYPE.TYPE_CODE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode == null ? null : typeCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.TYPE_NAME
     *
     * @return the value of ORGANIZATION_TYPE.TYPE_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getTypeName() {
        return typeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.TYPE_NAME
     *
     * @param typeName the value for ORGANIZATION_TYPE.TYPE_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setTypeName(String typeName) {
        this.typeName = typeName == null ? null : typeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.CREATE_TIME
     *
     * @return the value of ORGANIZATION_TYPE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.CREATE_TIME
     *
     * @param createTime the value for ORGANIZATION_TYPE.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORGANIZATION_TYPE.UPDATE_TIME
     *
     * @return the value of ORGANIZATION_TYPE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORGANIZATION_TYPE.UPDATE_TIME
     *
     * @param updateTime the value for ORGANIZATION_TYPE.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}