package com.cn.interfacedocument.entity;

import java.util.Date;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.PASSWORD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.TOKEN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String token;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.IS_LOGIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String isLogin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.HEAD_PORTRAIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String headPortrait;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.INTEGRAL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long integralId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.ID
     *
     * @return the value of USER.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.ID
     *
     * @param id the value for USER.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.NAME
     *
     * @return the value of USER.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.NAME
     *
     * @param name the value for USER.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.EMAIL
     *
     * @return the value of USER.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.EMAIL
     *
     * @param email the value for USER.EMAIL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.PASSWORD
     *
     * @return the value of USER.PASSWORD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.PASSWORD
     *
     * @param password the value for USER.PASSWORD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.TOKEN
     *
     * @return the value of USER.TOKEN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.TOKEN
     *
     * @param token the value for USER.TOKEN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.IS_LOGIN
     *
     * @return the value of USER.IS_LOGIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIsLogin() {
        return isLogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.IS_LOGIN
     *
     * @param isLogin the value for USER.IS_LOGIN
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIsLogin(String isLogin) {
        this.isLogin = isLogin == null ? null : isLogin.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.HEAD_PORTRAIT
     *
     * @return the value of USER.HEAD_PORTRAIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getHeadPortrait() {
        return headPortrait;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.HEAD_PORTRAIT
     *
     * @param headPortrait the value for USER.HEAD_PORTRAIT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setHeadPortrait(String headPortrait) {
        this.headPortrait = headPortrait == null ? null : headPortrait.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.INTEGRAL_ID
     *
     * @return the value of USER.INTEGRAL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getIntegralId() {
        return integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.INTEGRAL_ID
     *
     * @param integralId the value for USER.INTEGRAL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIntegralId(Long integralId) {
        this.integralId = integralId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CREATE_DATE
     *
     * @return the value of USER.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CREATE_DATE
     *
     * @param createDate the value for USER.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.CREATE_TIME
     *
     * @return the value of USER.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.CREATE_TIME
     *
     * @param createTime the value for USER.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER.UPDATE_TIME
     *
     * @return the value of USER.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER.UPDATE_TIME
     *
     * @param updateTime the value for USER.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}