package com.cn.interfacedocument.entity;

import java.util.Date;

public class UserAuthenticate {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_AUTHENTICATE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_AUTHENTICATE.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String actualName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_AUTHENTICATE.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String idCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_AUTHENTICATE.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USER_AUTHENTICATE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_AUTHENTICATE.ID
     *
     * @return the value of USER_AUTHENTICATE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_AUTHENTICATE.ID
     *
     * @param id the value for USER_AUTHENTICATE.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_AUTHENTICATE.ACTUAL_NAME
     *
     * @return the value of USER_AUTHENTICATE.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getActualName() {
        return actualName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_AUTHENTICATE.ACTUAL_NAME
     *
     * @param actualName the value for USER_AUTHENTICATE.ACTUAL_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setActualName(String actualName) {
        this.actualName = actualName == null ? null : actualName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_AUTHENTICATE.ID_CARD
     *
     * @return the value of USER_AUTHENTICATE.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getIdCard() {
        return idCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_AUTHENTICATE.ID_CARD
     *
     * @param idCard the value for USER_AUTHENTICATE.ID_CARD
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setIdCard(String idCard) {
        this.idCard = idCard == null ? null : idCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_AUTHENTICATE.CREATE_DATE
     *
     * @return the value of USER_AUTHENTICATE.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_AUTHENTICATE.CREATE_DATE
     *
     * @param createDate the value for USER_AUTHENTICATE.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USER_AUTHENTICATE.NAME
     *
     * @return the value of USER_AUTHENTICATE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USER_AUTHENTICATE.NAME
     *
     * @param name the value for USER_AUTHENTICATE.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}