package com.cn.interfacedocument.entity;

import java.util.Date;

public class Video {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String content;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long lawCaseId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long lawMeettingId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.END_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Date endTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long personnelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.STREAM_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String streamId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.APPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private String apply;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column VIDEO.NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private byte[] nemessage;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.ID
     *
     * @return the value of VIDEO.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.ID
     *
     * @param id the value for VIDEO.ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.NAME
     *
     * @return the value of VIDEO.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.NAME
     *
     * @param name the value for VIDEO.NAME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.CONTENT
     *
     * @return the value of VIDEO.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.CONTENT
     *
     * @param content the value for VIDEO.CONTENT
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setContent(String content) {
        this.content = content == null ? null : content.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.TYPE
     *
     * @return the value of VIDEO.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.TYPE
     *
     * @param type the value for VIDEO.TYPE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.URL
     *
     * @return the value of VIDEO.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.URL
     *
     * @param url the value for VIDEO.URL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.LAW_CASE_ID
     *
     * @return the value of VIDEO.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getLawCaseId() {
        return lawCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.LAW_CASE_ID
     *
     * @param lawCaseId the value for VIDEO.LAW_CASE_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLawCaseId(Long lawCaseId) {
        this.lawCaseId = lawCaseId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.CREATE_DATE
     *
     * @return the value of VIDEO.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.CREATE_DATE
     *
     * @param createDate the value for VIDEO.CREATE_DATE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.CREATE_TIME
     *
     * @return the value of VIDEO.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.CREATE_TIME
     *
     * @param createTime the value for VIDEO.CREATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.UPDATE_TIME
     *
     * @return the value of VIDEO.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.UPDATE_TIME
     *
     * @param updateTime the value for VIDEO.UPDATE_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.LAW_MEETTING_ID
     *
     * @return the value of VIDEO.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getLawMeettingId() {
        return lawMeettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.LAW_MEETTING_ID
     *
     * @param lawMeettingId the value for VIDEO.LAW_MEETTING_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLawMeettingId(Long lawMeettingId) {
        this.lawMeettingId = lawMeettingId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.END_TIME
     *
     * @return the value of VIDEO.END_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Date getEndTime() {
        return endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.END_TIME
     *
     * @param endTime the value for VIDEO.END_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.PERSONNEL_ID
     *
     * @return the value of VIDEO.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getPersonnelId() {
        return personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.PERSONNEL_ID
     *
     * @param personnelId the value for VIDEO.PERSONNEL_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setPersonnelId(Long personnelId) {
        this.personnelId = personnelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.STREAM_ID
     *
     * @return the value of VIDEO.STREAM_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getStreamId() {
        return streamId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.STREAM_ID
     *
     * @param streamId the value for VIDEO.STREAM_ID
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setStreamId(String streamId) {
        this.streamId = streamId == null ? null : streamId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.APPLY
     *
     * @return the value of VIDEO.APPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public String getApply() {
        return apply;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.APPLY
     *
     * @param apply the value for VIDEO.APPLY
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setApply(String apply) {
        this.apply = apply == null ? null : apply.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column VIDEO.NEMESSAGE
     *
     * @return the value of VIDEO.NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public byte[] getNemessage() {
        return nemessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column VIDEO.NEMESSAGE
     *
     * @param nemessage the value for VIDEO.NEMESSAGE
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setNemessage(byte[] nemessage) {
        this.nemessage = nemessage;
    }
}