package com.cn.interfacedocument.entity;

public class XjqLocksKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XJQ_LOCKS.SCHED_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String schedName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XJQ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    private String lockName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XJQ_LOCKS.SCHED_NAME
     *
     * @return the value of XJQ_LOCKS.SCHED_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getSchedName() {
        return schedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XJQ_LOCKS.SCHED_NAME
     *
     * @param schedName the value for XJQ_LOCKS.SCHED_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setSchedName(String schedName) {
        this.schedName = schedName == null ? null : schedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XJQ_LOCKS.LOCK_NAME
     *
     * @return the value of XJQ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public String getLockName() {
        return lockName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XJQ_LOCKS.LOCK_NAME
     *
     * @param lockName the value for XJQ_LOCKS.LOCK_NAME
     *
     * @mbggenerated Fri Nov 30 10:52:04 CST 2018
     */
    public void setLockName(String lockName) {
        this.lockName = lockName == null ? null : lockName.trim();
    }
}