package com.cn.interfacedocument.entity;

public class XjqSchedulerState extends XjqSchedulerStateKey {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XJQ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long lastCheckinTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column XJQ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    private Long checkinInterval;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XJQ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @return the value of XJQ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getLastCheckinTime() {
        return lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XJQ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @param lastCheckinTime the value for XJQ_SCHEDULER_STATE.LAST_CHECKIN_TIME
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setLastCheckinTime(Long lastCheckinTime) {
        this.lastCheckinTime = lastCheckinTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column XJQ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @return the value of XJQ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public Long getCheckinInterval() {
        return checkinInterval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column XJQ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @param checkinInterval the value for XJQ_SCHEDULER_STATE.CHECKIN_INTERVAL
     *
     * @mbggenerated Fri Nov 30 10:52:03 CST 2018
     */
    public void setCheckinInterval(Long checkinInterval) {
        this.checkinInterval = checkinInterval;
    }
}